name: linkedin

on:
  schedule:
    - cron: '12 13 * * 1'
  workflow_dispatch:


jobs:
  post:
    runs-on: windows-latest
    env:
      LI_CLIENT_ID: ${{ secrets.LI_CLIENT_ID}}
      LI_CLIENT_SECRET: ${{ secrets.LI_CLIENT_SECRET}}
      LI_REFRESH_TOKEN: ${{ secrets.LI_REFRESH_TOKEN}}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      - name: Post to LinkedIn.
        run: Rscript runner-li.R
