name: social-post

on:
  workflow_dispatch:


jobs:
  tweet:
    runs-on: windows-latest
    env:
      TTBOT_API_KEY: ${{ secrets.TTBOT_API_KEY }}
      TTBOT_API_SECRET: ${{ secrets.TTBOT_API_SECRET }}
      TTBOT_ACCESS_TOKEN: ${{ secrets.TTBOT_ACCESS_TOKEN }}
      TTBOT_ACCESS_TOKEN_SECRET: ${{ secrets.TTBOT_ACCESS_TOKEN_SECRET }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      - name: Install and activate renv
        run: |
          install.packages("renv")
          renv::activate()
        shell: Rscript {0}
      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}
      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
      - name: Restore packages
        run: Rscript -e 'renv::restore()'
      - name: Create and post tweet
        run: Rscript tweet.R
