name: toot

on:
  schedule:
    - cron: '12 13 * * 1'
  workflow_dispatch:


jobs:
  post:
    runs-on: windows-latest
    env:
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_TOKEN }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      - name: Toot.
        run: Rscript runner-toot.R
